"""Resolving which code a job actually runs — and refusing to guess.

## The failure this exists to prevent

The image ships dependencies; the volume ships code. `PYTHONPATH=/workspace/code:/app` puts
the volume ahead of the baked copy, so editing a stage is a few-KB upload rather than a 5 GB
rebuild.

When the sync did not happen, that arrangement does not error. It silently runs the BAKED
code while you believe you are running what you just pushed — a stage succeeding against the
wrong version, which is the same class of failure `framework.py` was written to catch.

So: if a spec names a code root, that root must exist and contain Python, or the job refuses
to start. A missing code root is never treated as "fall back to whatever is baked in".

## Immutable roots

CI publishes to `code/<repo>/<sha>/`, never rewriting a directory. That matters because a
push to a mutable path can change code under a running job, and Python's lazy imports mean a
module loaded at stage 4 could be a different version than the one loaded at stage 1 —
non-deterministic and unreproducible. `code/<repo>/dev/` is mutable on purpose, for
iteration, and a job that used it records that it did.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class CodeRoot:
    path: Path | None
    rev: str = ""
    source: str = "baked"          # volume | baked
    py_files: int = 0
    capabilities: dict | None = None
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems

    def as_dict(self) -> dict:
        return {"path": str(self.path) if self.path else None, "rev": self.rev,
                "source": self.source, "py_files": self.py_files,
                "has_capabilities": self.capabilities is not None,
                "problems": self.problems}


def workspace_root() -> Path:
    return Path(os.environ.get("PODH_WORKSPACE", "/workspace"))


def resolve(spec: dict | None = None, *, env_root: str | None = None) -> CodeRoot:
    """Work out where the job's code lives.

    Order: an explicit `spec.code.root` wins; then `PODH_CODE_ROOT`; then the baked `/app`.
    A relative root is taken against the workspace, so a spec can say
    `code/lingua-trainer/a1b2c3d` without knowing the mount point.
    """
    declared = ((spec or {}).get("code") or {}).get("root") or ""
    rev = ((spec or {}).get("code") or {}).get("rev") or ""
    raw = declared or env_root or os.environ.get("PODH_CODE_ROOT", "")

    if not raw:
        return CodeRoot(path=None, rev="", source="baked")

    p = Path(raw)
    if not p.is_absolute():
        p = workspace_root() / raw

    cr = CodeRoot(path=p, rev=rev, source="volume")

    if not p.exists():
        cr.problems.append(
            f"code root {p} does not exist. The code was probably never synced — "
            f"run `runctl sync` or check code.root in the spec. Refusing to fall back to "
            f"the baked image code, which would run the wrong version silently.")
        return cr
    if not p.is_dir():
        cr.problems.append(f"code root {p} is not a directory")
        return cr

    cr.py_files = sum(1 for _ in p.rglob("*.py"))
    if cr.py_files == 0:
        cr.problems.append(
            f"code root {p} contains no .py files — an empty or partial sync")

    caps = p / "capabilities.json"
    if caps.exists():
        try:
            cr.capabilities = json.loads(caps.read_text(encoding="utf-8"))
            if not cr.rev:
                cr.rev = cr.capabilities.get("rev", "")
        except json.JSONDecodeError as exc:
            cr.problems.append(f"capabilities.json is not valid JSON: {exc}")

    # A mutable dev root is legitimate, but the job should record that it used one — "which
    # code ran" is otherwise unanswerable after the fact.
    if not cr.rev and p.name == "dev":
        cr.rev = "dev(mutable)"
    return cr


def pythonpath(cr: CodeRoot, *, base: str = "/app") -> str:
    """The PYTHONPATH a job should run with. Volume first, baked second."""
    parts = [str(cr.path)] if cr.path and cr.ok else []
    parts.append(base)
    existing = os.environ.get("PYTHONPATH", "")
    if existing:
        parts.extend(x for x in existing.split(":") if x and x not in parts)
    return ":".join(parts)


def load_capabilities(cr: CodeRoot) -> dict | None:
    """The workload's published stage manifest, if it has one.

    Generated by CI from the stage registry, so the control plane and `/v1/` discovery can
    know the stage vocabulary WITHOUT importing the workload — which is what makes shallow
    dry-run possible off-pod.
    """
    return cr.capabilities
